# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: '2.1'

services:

  bev-shell:
    build:
      context: .
      dockerfile: ./shell/Dockerfile
    image: sawtooth-simple-supply-shell
    container_name: bev-shell
    volumes:
      - .:/project/bev
      - /project/bev/volby/node_modules
    command: |
      bash -c "
        simple-supply-protogen
        cd volby/
        npm run build
        cd ../
        tail -f /dev/null
      "

  bev-tp:
    build:
        context: .
        dockerfile: ./processor/Dockerfile
    image: sawtooth-simple-supply-tp
    container_name: bev-tp
    volumes:
      - '.:/project/bev'
    depends_on:
      - bev-shell
    command: |
      bash -c "
        sleep 1
        simple-supply-tp -v -C tcp://validator:4004
      "

  bev-rest-api:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile
    image: sawtooth-simple-supply-rest-api
    container_name: bev-rest-api
    volumes:
      - .:/project/bev
    ports:
      - '8000:8000'
    depends_on:
      - bev-shell
    command: |
      bash -c "
        simple-supply-rest-api \
          -B bev-rest-api:8000 \
          -C validator:4004 \
          --db-host postgres \
          -vv
      "

  bev-subscriber:
    build:
      context: .
      dockerfile: ./subscriber/Dockerfile
    image: sawtooth-simple-supply-subscriber
    container_name: bev-subscriber
    volumes:
      - '.:/project/bev'
    depends_on:
      - bev-shell
      - postgres
    command: |
      bash -c "
        simple-supply-subscriber init \
          --db-host postgres \
          -vv
        sleep 3
        bev-subscriber subscribe \
          --db-host postgres \
          -C tcp://validator:4004 \
          -vv
      "

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.2
    container_name: bev-settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.2
    container_name: rest-api
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -vv -C tcp://validator:4004 --bind rest-api:8008

  validator:
    image: hyperledger/sawtooth-validator:1.2
    container_name: bev-validator
    expose:
      - 4004
    ports:
      - '4004:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          sawtooth keygen my_key
          sawset genesis -k /root/.sawtooth/keys/my_key.priv
          sawset proposal create -k /root/.sawtooth/keys/my_key.priv \
            sawtooth.consensus.algorithm.name=Devmode \
            sawtooth.consensus.algorithm.version=0.1 \
            -o config.batch
          sawadm genesis config-genesis.batch config.batch
        fi;
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050
      "

  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust:1.2
    expose:
      - 5050
    ports:
      - '5050:5050'
    container_name: bev-devmode-engine-rust-default
    depends_on:
      - validator
    entrypoint: devmode-engine-rust --connect tcp://validator:5050

  postgres:
    image: postgres:alpine
    container_name: bev-postgres
    restart: always
    environment:
      POSTGRES_USER: sawtooth
      POSTGRES_PASSWORD: sawtooth
      POSTGRES_DB: bev
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    container_name: bev-adminer
    restart: always
    ports:
      - '8080:8080'

  volby:
    build: ./volby
    image: simple-supply-curator-app
    container_name: volby
    volumes:
      - ./volby/public/:/usr/local/apache2/htdocs/
    expose:
      - 80
    ports:
      - '8040:80'
    depends_on:
      - bev-shell
      - bev-rest-api
